export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpg",
      username: "M Bhuvaneswari",
    },
    {
      id:2,
      profilePicture: "assets/person/3.jpg",
      username: "J Shivaya",
    },
    {
      id:3,
      profilePicture: "assets/person/2.jpg",
      username: "Anish-J ",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpg",
      username: "D Muktakesha",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Maha Gauri",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpg",
      username: "Rudra Priya",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpg",
      username: "Shambhu Jn",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Anand Krishna ",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpg",
      username: "K. Binayak Thakur",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Safal Khand" ,
    },
    {
      id:11,
      profilePicture: "assets/person/1.jpg",
      username: "Anandini ",
    },
    {
      id:12,
      profilePicture: "assets/person/8.jpeg",
      username: "Gangajamuna",
    },
    {
      id:13,
      profilePicture: "assets/person/9.jpg",
      username: "Sima sharma" ,
    },
    {
      id:14,
      profilePicture: "assets/person/8.jpeg",
      username: "Aradhya Roy",
    },
    {
      id:15,
      profilePicture: "assets/person/9.jpg",
      username: "Vihaan K",
    },
    {
      id:16,
      profilePicture: "assets/person/10.jpeg",
      username: "Harsh Jain" ,
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
    {
      id: 11,
      desc: "Just Wow...!!",
      photo: "assets/post/11.jpg",
      date: "4 days ago",
      userId: 11,
      like: 150,
      comment: 100,
    },
  ];
  